Feat/block blog page
chetanverma16/react-portfolio-template pull request #69
Opened 2022-07-31 09:27 UTC by achu-krishna

Added the feature to redirect from the blog page when url is entered to the previous page.

closes #68

2022-08-02 15:33 UTC, chetanverma16 requested changes
Awesome PR!
Everything looks good we can merge once the above is resolved

2022-08-02 15:59 UTC, chetanverma16 commented on pages/blog/index.js
> +    else router.back();
`router.push("/")`

2022-08-07 01:52 UTC, achu-krishna commented
@chetanverma16 made the requested changes.

2022-08-07 11:44 UTC, chetanverma16 approved these changes
Awesome work!

2022-08-07 11:44 UTC, merged